### ISSUE TITLE
Keep copy of original numbering

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#1019]
When builiding, resid numbering changes. Sometimes it is convenient to keep it as the numbering is somewhat consensual and not arbitrary. It should be trivial to map residues after buillding to residues before builiding and store that mapping somewhere to interconvert any time is needed.

**Comment by stefdoerr** [comment]
I cannot really renumber them back because it might cause issues with other residue number like caps. But I decided to generate a CSV file in the build folder which reports the matching of protein/nucleic residues to their original numbers. 
Done here:
https://github.com/Acellera/htmd/commit/df65bc7dc658c74a673afec6ab694af5d50d2a2c

Example:
```
new_resid,old_resid,old_insertion,old_chain
2,16,,A
3,17,,A
4,18,,A
5,19,,A
6,20,,A
7,21,,A
8,22,,A
```

**Comment by alejandrovr** [comment]
This should be enough, thanks!!!
