### ISSUE TITLE
Question regarding ITS plots

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#1023]
Hello,

I have a possibly basic question regarding the implied timescale plots in MSM analysis.
For several of my systems the ITS looks like in the figure attached: smooth, converged, and well defined for most of the plot except for the very last part of the lag time range, where the implied relaxation time curves spike. Nonetheless , the chapman-kolmogorov tests look perfect.
This behavior occurs quite often but I could never explain it, and now I have a referee complaining about these results.
All I could find out there were the possibilities that:
1) my system is undersampled 
2) the slow transitions are not reversibly sampled
3) I might need to consider hidden Markov models

I have seen, however, that in your tutorials you often obtain ITS plots similar to mine and you never discuss it. Can you provide some insight from your expert point of view?

Many thanks in advance!
Sergio

![dhaaht_1d timescales](https://user-images.githubusercontent.com/33486210/152533450-f774fdf4-31af-4958-8316-c2edfc7025c9.png)

**Comment by stefdoerr** [comment]
Ah yes sure. The ITS will always fail close to the end. The reason is that the lag time is reaching close to the length of your trajectories. This means that you end up with very few transition counts in your transition matrix so the statistics are garbage and you get noise in the plots. The lag time means you "jump" over conformations when counting state transitions. If you jump too far eventually the simulation doesn't have enough samples for good statistics. i.e. if your sim has 5 frames and you have a lag of 1 you get 4 transitions (1-2, 2-3, 3-4, 4-5). if you set a lag of 3 you have (1-4, 2-5) and the sim finished. so you only got two transitions with lag time 5 version 5 transitions with lag time 1.

You can avoid this in the plot by specifying the lag-time range to be a bit shorter in the plot command, for example to only plot up to 30ns in your case.
It's not an issue with your simulation, these ITS are fine (except maybe the fact that the slowest process is very fast but that might just be your system if there are no slow processes overall).

**Comment by smar966** [comment]
OK, that makes sense. All is clear now.
Thanks a lot!
