### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#103]
https://travis-ci.org/multiscalelab/htmd/jobs/154099862

Any clue?

**Comment by j3mdamas** [comment]
I'll try restart the build and see if it fails again (since it was just one)

**Comment by j3mdamas** [comment]
I'll try to understand why there is a `__pycache__` inside `parameterization/share/bin`. That's what is failing.

**Comment by j3mdamas** [comment]
This is black magic to me. After Matt did 52ff347c2386422384c46a4e18d45685105bfcd5, the fail appeared https://travis-ci.org/Acellera/htmd/builds/152932790. But his change has nothing to do with this...

It just fails on Linux 3.4 (Linux 3.5 and OSX 3.4 pass well). Apparently, after install, the package comes with a `__pycache__` on the `parameterization/share/bin`, and it fails one of the tests (`check_static.sh`), because the `__pycache__` is not expected to be there and the `ldd` does not give the expected output.

Maybe I should just fix it (in a clunky way) instead of trying to understand it...

More tomorrow.

**Comment by stefdoerr** [comment]
Pycache folders should not be on GitHub and can be safely removed afaik

On August 22, 2016 7:52:40 PM GMT+02:00, "João M. Damas" <notifications@github.com> wrote:
>This is black magic to me. After Matt did
>52ff347c2386422384c46a4e18d45685105bfcd5, the fail appeared
>https://travis-ci.org/Acellera/htmd/builds/152932790. But his change
>has nothing to do with this...
>
>It just fails on Linux 3.4 (Linux 3.5 and OSX 3.4 pass well).
>Apparently, after install, the package comes with a `__pycache__` on
>the `parameterization/share/bin`, and it fails one of the tests
>(`check_static.sh`), because the `__pycache__` is not expected to be
>there and the `ldd` does not give the expected output.
>
>Maybe I should just fix it (in a clunky way) instead of trying to
>understand it...
>
>More tomorrow.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/103#issuecomment-241494302

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by j3mdamas** [comment]
well, neither is `share/bin` in GitHub. Created during building. I assume `__pycache__` is also being created in the process, but weirdly only on this particular build.

actually, on `htmd/package/htmd/build.sh`, there's a command to get rid of `__pycache__` files after the C compiling
> `find htmd -type d -name __pycache__ -exec rm -rf {} \; -print || true`

**Comment by j3mdamas** [comment]
ok, I am going to change the file that is checking the binaries to ignore `__pycache__` files

**Comment by j3mdamas** [comment]
Fixed: https://travis-ci.org/multiscalelab/htmd/builds/154730789

Merging to acellera/htmd:master because it's also failing there

**Comment by mj-harvey** [comment]
fixed
