### ISSUE TITLE
charmm.build problem

### ISSUE THREAD

**Issue by suice07** [Acellera/htmd#1057]
Hey guys,

I am totally new to htmd and trying with those tutorials, I noticed that , in the" System building: Protein in Membrane with Ligand" section , the ligand with resname 'BEN' was seperated from the protein itself. and using the command below to build topology for the ligand.
`topos_charmm  = charmm.defaultTopo() + [join(datadir, 'BEN.rtf')]
params_charmm = charmm.defaultParam() + [join(datadir, 'BEN.prm')]`

I did not have the *.trf and *.prm before that. how can I generated them? I notice that there is a function named `charmm.search`,is it used for searching the topology files? what if there is no resname for the molecule I inserted to the protein?

is there any simple way to build topology for the ligand-protein sovalted box ?when I use charmm.build for the whole complex, there is an error: "Info: generating structure...psfgen) unknown residue type BEN
failed!"
It will be really nice if any help was offered, thanks in advance

**Comment by stefdoerr** [comment]
If you want to build systems with custom ligands you need to get their parameters from somewhere. We currently provide a tool for generating small molecule parameters for AMBER forcefields which is parameterize https://www.playmolecule.com/parameterize/

If you want to instead produce an rtf/prm for CHARMM you will have to use `match` https://brooks.chem.lsa.umich.edu/index.php?matchserver=submit but we don't officially support CHARMM anymore due to licensing issues.

**Comment by suice07** [comment]
ok,thanks a lot@stefdoerr
