### ISSUE TITLE
Trouble installing: htmd does not exist

### ISSUE THREAD

**Issue by MarioAsti8** [Acellera/htmd#1080]
I tried to install HTMD using the commands in the documentation. However, it wasn't able to find the package:

mamba install htmd -c acellera -c conda-forge

Could not solve for environment specs
The following package could not be installed
└─ htmd does not exist (perhaps a typo or a missing channel).

Any clue? Thanks!

**Comment by stefdoerr** [comment]
HTMD does not exist for Windows. There are a few of its dependencies which don't exist on Windows. You can try installing it manually from the repository but I can't guarantee it will work. I might take a look at it next week to see if nowadays the dependencies have made Windows releases but no promises as we can't provide support for it either.

**Comment by stefdoerr** [comment]
Hey, HTMD now exists for Windows! I cannot offer any real support though since I don't use Windows and also it's missing some important dependencies like ACEMD (for the simulations), AmberTools (for building AMBER systems) and PLUMED (for doing complex trajectory analyses). But feel free to give it a try if you want.
