### ISSUE TITLE
Choice of hyperparameters

### ISSUE THREAD

**Issue by driesvr** [Acellera/htmd#152]
Hi,
I'm working on a protein - ligand binding simulation in a similar fashion to the tutorial example. I'm wondering how the hyperparameters (the tica lagtime, for example) used there are selected? 

Thanks,

Dries

**Comment by stefdoerr** [comment]
The tica lagtime is kind of arbitrary. If you read the original papers published by Pande and Noe they both claimed that the lagtime didn't have a very large effect. In some further presentations however they showed a heuristic for choosing a lagtime by plotting the auto-correlations of the input features and then choosing a lagtime at which there was a clear gap between slowly decorrelating and fast decorrelating features so as to separate slow from fast processes. I typically use something between 2 and 20 ns but it is indeed arbitrarily chosen.

TICA dimensions can theoretically be chosen to cover 95% of the kinetic variance (kind of like people do with PCA). If you don't provide number of dimensions in the `tica.project()` method it will do that. However in my experience this works real bad because it ends up projecting on 100s of dimensions and I am working on a paper that shows that this makes for really bad projections. (Caflish found the same in a paper). Practically TICA seems to work best for around 2-5 dimensional projections.

As for MSM hyperparameters these are a bit more established. MSM lagtime is chosen when the implied timescales start converging and number of macrostates chosen by the timescale separation.
