### ISSUE TITLE
new docs overshoot my screen on my laptop

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#155]
and there is no scrollbar to reach further right

**Comment by stefdoerr** [comment]
Get a decent laptop :D just kidding but yeah that's what happens when you go from 1100 to 1300 pixels. Weird though because the scrollbar worked when I tried resizing it on my desktop. I'll try fixing it

On October 11, 2016 10:17:20 PM GMT+02:00, Gianni De Fabritiis <notifications@github.com> wrote:
>and there is no scrollbar to reach further right
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/155

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by stefdoerr** [comment]
Was fixed a while back
