### ISSUE TITLE
Error estimates and model validation

### ISSUE THREAD

**Issue by driesvr** [Acellera/htmd#192]
Hi guys,
I have a few more issues that I'd love some help on. For model validation I'd like to do a chapman-komolgorov test. However, it looks like there's no way to do so within HTMD?
I'd also like to obtain an error estimate on the DeltaG value for my protein:ligand complex. Is there a builtin way to do this or can I perhaps just use bootstrapping?

Thanks in advance

Dries

**Comment by j3mdamas** [comment]
For error estimate, you can do "manual" bootstrapping. We already have a [bootstrap method](https://www.htmd.org/docs/latest/htmd.metricdata.html?highlight=bootstrap#htmd.metricdata.MetricData.bootstrap), which what really does it just the resampling. Then you can do the statistics. We want to implement an automatic tool, but we're still discussing the implementation and will probably only appear on 1.8.x or so.

About the first one, I don't think there is, but I am sure that there should be a way using pyemma together with HTMD. @stefdoerr could probably have a more detailed answer for you.

João

**Comment by stefdoerr** [comment]
Hey @driesvr sorry for the late reply.

You can access all PyEMMA MaximumLikelihoodMSM functions from Model.msm  
http://www.emma-project.org/latest/api/generated/pyemma.msm.MaximumLikelihoodMSM.html?highlight=cktest#pyemma.msm.MaximumLikelihoodMSM.cktest

And plot with this function
http://www.emma-project.org/latest/api/generated/pyemma.plots.plot_cktest.html?highlight=cktest#pyemma.plots.plot_cktest

```python
ck = model.msm.cktest(model.macronum)
from pyemma.plots import plot_cktest
plot_cktest(ck)
```

I don't trust this too much though because I just tried for fun to ask for 20 sets (even though I only have 5 macrostates) and it didn't error.

**Comment by stefdoerr** [comment]
Edit: now I understand. cktest actually does PCCA internally so it calculates as many macrostates as you ask it. So when I asked for 20 it actually calculated 20 states. Ok, so it makes sense.
