### ISSUE TITLE
HTMD website examples must be CI tests

### ISSUE THREAD

**Issue by mj-harvey** [Acellera/htmd#208]
Pace issue #207  , release 1.5.4 broke with the very first example on the htmd web page.
The *exact* examples on the website should be CI tests so we get some warning if they break. 
It's not acceptable to put out even a devel release where this very basic functionality is broken.

**Comment by j3mdamas** [comment]
I can make that example a test, it's OK.

But it wouldn't cause any warning for us in this particular case, because 1.5.4 worked when released, with a particular version of htmd-pdb2pqr, and 1.5.5 worked when released, with another particular version of htmd-pdb2pqr. The concern here is version compatibility between software codes.

**Comment by mj-harvey** [comment]
Ok, then I'll do a better job of encoding version requirements in the conda packaging.

**Comment by stefdoerr** [comment]
It's not so easy. At least for the full examples since they have loads of data dependencies and take a long while to execute. The basics tutorials though we should make testable
