### ISSUE TITLE
Issue with babel executable in dock function

### ISSUE THREAD

**Issue by jeiros** [Acellera/htmd#257]
The [dock](https://github.com/Acellera/htmd/blob/master/htmd/dock.py) function is failing when using the babel command to convert molecules from pdb to pdbqt format. I'm just running similar commands of the tutorial to my system like:
```python
from htmd import *
prot = Molecule('prot.pdb')
lig = Molecule('lig.pdb')
dock(prot, lig)
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-25-15f1092a95a5> in <module>()
----> 1 dock(prot, lig)

/home/je714/anaconda3/envs/htmd/lib/python3.5/site-packages/htmd/dock.py in dock(protein, ligand, center, extent, numposes, babelexe, vinaexe)
    146     os.remove(protein_pdbqt)
    147     os.remove(ligand_pdbqt)
--> 148     os.remove(output_pdbqt)
    149 
    150     return poses, np.array(scoring)

FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgi4qch77.pdbqt'
```
I copied over the dock function to modify it and found out that the [call to the babel command](https://github.com/Acellera/htmd/blob/master/htmd/dock.py#L103) is failing.
I use this new lines to see what's happening:
```python
    print('babelexe', babelexe)
    out1 = call([babelexe, '-i', 'pdb', protein_pdb, '-o', 'pdbqt', protein_pdbqt, '-xr'])
    print('out1', out1)
    out2 = call([babelexe, '-i', 'pdb', ligand_pdb, '-o', 'pdbqt', ligand_pdbqt, '-xhn'])
    print('out2', out2)
```
And this is the output
```python

babelexe /home/je714/anaconda3/envs/htmd/bin/babel
out1 -4
out2 -4
```
Also if I copy the `babel` call directly int the command line, I get a `Illegal instruction (core dumped)` error. Anyone seen this before?

**Comment by j3mdamas** [comment]
Can you `conda list babel`?

**Comment by mj-harvey** [comment]
The openbabel package requires a processor with avx. You'll have to compile/install an openbabel of your own.

**Comment by jeiros** [comment]
Hi @j3mdamas, this is the output:
```
$ conda list babel
# packages in environment at /home/je714/anaconda3/envs/htmd:
#
babel                     2.3.4                    py35_0
openbabel                 2015.09                  py35_1    acellera
```
@mj-harvey The `dock` function worked for me on the same machine (with no independent installation of openbabel) on a previous version of htmd (Python 3.4, htmd version  1.0.24), see my [previous issue](https://github.com/Acellera/htmd/issues/256).

**Comment by j3mdamas** [comment]
@jeiros wait a bit while I discuss with Matt.

Thanks for raising this issue.

**Comment by j3mdamas** [comment]
So, our current babel is just a copy from the openbabel from the omnia channel (for convinience of the user, so he doesn't need to specify the omnia channel). My guess is that the omnia openbabel does not work on your computer for a reason.

You can install the omnia openbabel package (`conda install openbabel -c omnia`), which will replace our own. If it works with their (which shouldn't), let us know. If it does not work (`Illegal instruction`), close this issue and create an issue here: https://github.com/omnia-md/conda-recipes/issues.

In this past, babel may have worked in your computer, because we were the ones distributing it: the babelexe was pointing to htmdbabel, a wrapper created by us to a binary distributed by us.

I know this is inconvenient, but it's the best we can do write now. Eventually we will replace the call to babel by internal code.

Thanks,
João
