### ISSUE TITLE
OSX package builds improvement

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#285]
If one wants to really support HTMD on OSX, there are stuff that need improving:

* building success of OSX HTMD on Travis (or change it to another builder system)
* building time of OSX HTMD
* make OSX work on py 3.6

**Comment by stefdoerr** [comment]
As per @tonigi 's suggestion:
1. Make htmd noarch
2. Build htmdlib on Travis separately

This will
1. Speed up a lot our testing/releasing since we can test it all on Linux
1. Reduce the mess with our distributions

For this we need:
1. a separate public repo which stealthily builds htmdlib (since it's private) like htmd does now. 
1. Low-level tests directly on htmdlib to test regressions under specific OSs.

**Comment by tonigi** [comment]
Let's see what Matt says. For me the biggest plus will be to cut the build complexity which is accumulating (and already biting I think).

**Comment by tonigi** [comment]
ehm.. adding a mention just to annoy @mj-harvey 
of course i can help if necessary

**Comment by j3mdamas** [comment]
So, htmd yesarch. Windows build on appveyor.

Let's make our tests faster
