### ISSUE TITLE
Change calls inside HTMD that require internet connection

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#298]
We cannot assume that the computer were HTMD is running has access to internet.

For now, I think that this one affects the __init__ and it solved with `HTMD_INTERACTIVE=1`. Still, I need to make that code robust enough so it doesn't error cryptically in case that environment variable is not set up

@stefdoerr, are there any other calls throughout HTMD that you remember that require internet?

**Comment by stefdoerr** [comment]
The news/version/license check, automatic PDB download, finding ligands in PDBs and finding mutations in PDBs. That should be all

**Comment by j3mdamas** [comment]
I need to check the current status, after changing registration

**Comment by j3mdamas** [comment]
Registration was changed a while ago. @stefdoerr will check if there are any calls that do not error gracefully

**Comment by stefdoerr** [comment]
All calls in cli.py are already caught and handled.

The only remaining ones are for PDB and OPM download and they give following error:

```python
MaxRetryError: HTTPConnectionPool(host='opm.phar.umich.edu', port=80): Max retries exceeded with url: /pdb/3ktv.pdb (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fe308089e80>: Failed to establish a new connection: [Errno -2] Name or service not known',))
```

There is no point in catching this because simply I would still need to print all this stuff to help someone out who has problems with these methods. I think it's clear enough the error.
