### ISSUE TITLE
have video tutorials link from htmd home page left panel

### ISSUE THREAD

**Issue by giadefa** [Acellera/htmd#304]
link youtube channel

**Comment by j3mdamas** [comment]
@gerardBCN, do you know how to do this?

**Comment by GerardBCN** [comment]
In principle the same way as https://www.htmd.org/docs/latest/acemd.commandreference.html was generated, which, by the way, is not working. You could easily create a page with youtube video embeds, in markdown is well documented. The reason why the link is not working has something to do with the fact that iframe inside has either the wrong link or the protocol used is http instead of https. When visiting a page using secure http I think is mandatory that links to other resources are also secured.

**Comment by j3mdamas** [comment]
this is a recurring problem, but youtube.com is https, so I think it won't be a problem.

But I don't think Gianni wanted a separate page, but rather like a tab on the left of the home page? That's more fancy stuff, no?

**Comment by GerardBCN** [comment]
That's what i thought: http://docs.acellera.com/acemd/commands/ is not secured, therefore not even changing it to https://docs.acellera.com/acemd/commands/ would yield any change. You should get a certificate for that page if you want to embed or simply substitute the iframe by a link, preferably with the target="_blank" directive as in:

<a href="http://docs.acellera.com/acemd/commands/" target="_blank">Link to Acellera ACEMD DOCS</a>

**Comment by GerardBCN** [comment]
You can modify the tree index somehwere in some rst file with custom links. Probably you would like a link to the acellera youtube page and that would suffice.

**Comment by GerardBCN** [comment]
use always target="_blank" when linking to external page. This will force the opening of a new window.

**Comment by j3mdamas** [comment]
For the acemd docs:

If it was `github.io` domain, I think I could do this: https://help.github.com/articles/securing-your-github-pages-site-with-https/. But since it's another domain, I think I need to ask Matt to enforce https on docs.acellera.com. Let's see how that goes.

For the youtube:

Can you come down and help me with it?

**Comment by j3mdamas** [comment]
When you have time, of course

**Comment by GerardBCN** [comment]
OK

**Comment by j3mdamas** [comment]
For Alejandro
