### ISSUE TITLE
Error visualizing molecullar complexes

### ISSUE THREAD

**Issue by edgarsanp** [Acellera/htmd#334]
In [2]: m = Molecule('2gfp_rect_dmpc.pdb')

In [3]: m.view()
/usr/local/lib/vmd/vmd_LINUXAMD64: /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1: no version information available (required by /usr/local/lib/vmd/vmd_LINUXAMD64)
couldn't read atom 6797

[2gfp_rect_dmpc.pdb.zip](https://github.com/Acellera/htmd/files/992627/2gfp_rect_dmpc.pdb.zip)

This command opened VMD showing a black screen. Using vmd with the terminal, the file was showed perfectly.

**Comment by stefdoerr** [comment]
Your PDB is broken. The resid overflows into the insertion field.
Check the docs: http://www.wwpdb.org/documentation/file-format-content/format33/sect9.html#ATOM
Resid should be columns 23-26. In your PDB at line 24901 you go into 4-digit resid and it overflows.

HTMD then makes a mess out of it since it cuts of that last digit from the resid and uses it as insertion number.

I would suggest using segments for the waters and resetting their resids every once in a while to not reach 4 digits. What program produced this PDB?

**Comment by edgarsanp** [comment]
Hi, Stefan. I've downloaded the PDB from the Charmm-GUI page. I tried with other PDB but I've had the same result.

http://www.charmm-gui.org/?doc=archive&lib=complex

**Comment by stefdoerr** [comment]
I added a small patch to HTMD so that it reads the file https://github.com/Acellera/htmd/commit/cf4b491a15cf89d3f6b036f76aa993feca79df1d. But it will be wrong because it will cut off the last digit of the resid. But at least it will load and visualize.

The only thing I can suggest you is to renumber all residues using the resid AND the insertion and then zero the insertion field. 
```python
from htmd.builder.builder import sequenceID
mol.resid = sequenceID((mol.resid, mol.insertion))
mol.insertion[:] = ''
```
This should make it work inside HTMD but you might have problems later on if you try to build it. Give it a try I guess.

The only "good" solution would be to write some manual code which resets resid numbers every few water molecules or something like that and puts them in separate segments.

**Comment by tonigi** [comment]
Perhaps loading the PSF avoids the problem?

**Comment by j3mdamas** [comment]
Yeah, this is a CHARMM-GUI problem, not an HTMD problem. They are the ones not producing a valid PDB file.

**Comment by stefdoerr** [comment]
Yup. It's been discussed before. Everyone likes to break PDB format in their own "cool" way so we just decide to not support any of that craziness :stuck_out_tongue:  Official or nothing.

**Comment by tonigi** [comment]
You may be able to use the PSF (from the .tar.gz file)

**Comment by stefdoerr** [comment]
Yeah, try loading it on top of the PDB like this:
```python
mol = Molecule('blabla.pdb')
mol.read('blabla.psf')
```
Might work

**Comment by edgarsanp** [comment]
Stefan, your proposal WORKS!

Sorry for replying so late, and thank you!
