### ISSUE TITLE
Disulfide detection should take account for residue insertion

### ISSUE THREAD

**Issue by j3mdamas** [Acellera/htmd#360]

**Comment by stefdoerr** [comment]
I could fix it with some work. I am wondering though if we should bother. This is fixed by renumbering the residues before building. After building (especially with AMBER) residues are renumbered anyways.

We assume in building in multiple places that the segid/resid combo is unique.
Maybe I should just error out in case of insertions and tell the user to renumber the residues?

**Comment by j3mdamas** [comment]
@cuzzo87, can you please put here a reproducible example?

**Comment by j3mdamas** [comment]
@cuzzo87, please?

**Comment by stefdoerr** [comment]
@cuzzo87 my god, at least answer :stuck_out_tongue: I need a test case to fix this

**Comment by stefdoerr** [comment]
Fixed in https://github.com/Acellera/htmd/commit/fca8741481c4b92d02d19680d4eddd1228889c93

Now the Molecule reader also throws a warning when reading residues and recommends to use the Molecule.renumberResidues() method https://github.com/Acellera/htmd/commit/0d24f87fa54b143bc16736f02ad145ea9b616821
