### ISSUE TITLE
MATCH fails due to missing bond types

### ISSUE THREAD

**Issue by raimis** [Acellera/htmd#408]
An original ligand [3ag9_ligand.mol2.txt](https://github.com/Acellera/htmd/files/1169318/3ag9_ligand.mol2.txt) file works with MATCH:
```bash
$ match-typer -charge 3 -forcefield top_all36_cgenff_new 3ag9_ligand.mol2
```
Read and write the file with HTMD:
```python
from htmd.ui import Molecule
Molecule('3ag9_ligand.mol2').write('3ag9_ligand_2.mol2')
```
Now MATCH fills the system memory and crashes:
```bash
$ match-typer -charge 3 -forcefield top_all36_cgenff_new 3ag9_ligand_2.mol2
```

The reason, HTMD does not preserve bond types:
```
@<TRIPOS>BOND
     1    2    1 ar 
     2    6    1 ar 
     3    3    2 ar 
```
```
@<TRIPOS>BOND
     1    1    2 un
     2    1    6 un
     3    2    3 un

```

**Comment by raimis** [comment]
@stefdoerr,

I can find where the bond types are read and written, but I'm not sure, how add a variable correctly into *Molecule* to store bond types.

**Comment by raimis** [comment]
This is related to #329

**Comment by j3mdamas** [comment]
This is issue #329. We can close this one.

**Comment by stefdoerr** [comment]
Hm are you sure it's the same issue Joao? @raimis has a point. We need to store the bond types, you cannot just guess them (at least not without some heuristics, can you?). We could add a Molecule.bondtype field which describes the type of each bond if available?

**Comment by j3mdamas** [comment]
Well, since these bond types are only used for MOL2 files, I was going to make it part of the MOL2write functionality. I see no reason, for now, to store them. Alternatively, yes, we could have them, and MOL2write would only write them.

The idea is that, if you read a PDB and write a MOL2, you should be able to re-create the right bond types, without needing to read them (since the PDB has no info on them)

**Comment by stefdoerr** [comment]
So you want to guess the bond types then.

You need to be able to recognize aromatic bonds and such stuff for example. It's not exactly trivial but there are rules for it if someone feels like implementing them.

**Comment by j3mdamas** [comment]
yes, that would be idea and the reason is not done yet (not trivial). If it's fairly general, it can be moved to another method/function, but for now I would like to contain it inside the MOL2write.

I know that we are doing ring detection in the parameterization module, Matt has implemented it for detecting "soft" torsions. I would guess this bond type guessing would actually be useful for that, as @raimis already mentioned, the double bonds are being considered as "soft" torsions through that implementation.

**Comment by stefdoerr** [comment]
I would follow a procedure as with the element field. Store explicit bond
types read from file and guess missing types. I think it's safer that way
than assuming that our heuristics are better than the explicit information
stored by the chemist

**Comment by j3mdamas** [comment]
Will keep that in mind.
