### ISSUE TITLE
Too many frames causes crashing

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#436]
Hi,

I am working with simulations (.xtc) with 100 000 frames (45 000 atoms with water) in them. Trying to operate these files with HTMD causes the system to crash due to memory limitations. This happens without a warning and somehow the memory keeps being reserved even after I have killed all the processes related to this, so a restart is required to free the memory. 

Is there a way I can read in only every 10th frame or something so I could analyse the files with HTMD? I guess the problem is that it tries to read all the trajectory into the memory and not just individual frames.

**Comment by stefdoerr** [comment]
there is the `skip` parameter to Molecule.read() method and Metric() class for skipping frames. The problem is that the trajectory has to be read in whole into memory first and then will the frames be skipped because many trajectory formats don't support random access to frames.

At which command does the memory fill up?

Also about the memory not freeing after killing python I find it very weird. This usually only happens with memory fragmentation but here you are trying to read a single large chunk of data into memory.

**Comment by piia600** [comment]
The memory fills up with any command that actually tries to do anything with the trajectory, such as filtering out waters or calculating a metric. 

The not-freeing of the memory is weird, but so far I haven't found any other way than restart to cope with it. Anyway, it would be nice to even get a warning before the system runs out of memory and crashes.

**Comment by stefdoerr** [comment]
Okay then use `skip=100` for example to keep only every 100th frame. That should make it work.

It's not really possible to warn before running out of memory. No program does that. That's an operating system issue. It can only warn when a single array would not fit into memory but if you create 1000 small arrays that fill up memory it cannot handle that.

**Comment by piia600** [comment]
Where do I exactly put this command? To the simlist, to the metric, to the filtering command?

**Comment by stefdoerr** [comment]
Read my above comment: https://github.com/Acellera/htmd/issues/436#issuecomment-324854921
So to the Metric() or to the Molecule.read() depending how you read the trajectories.

**Comment by piia600** [comment]
Yes, and how is this going to solve the problem? It still tries to load all the trajectory to the memory, which is the initial problem, and yes, it still crashes. It does not really matter that I would only use every 100th or every 1000th frames for the Metric, because HTMD still needs to load the whole trajectory to the memory. I am trying to calculate a distance between 2 atoms, so the resulting data matrix is of a very reasonable size.

**Comment by stefdoerr** [comment]
Sorry but you need to be more clear. That's why I asked you before where it crashes. Here you said https://github.com/Acellera/htmd/issues/436#issuecomment-324856622 that it only crashes when it tries to calculate stuff "filtering out waters or calculating a metric", not when it loads the trajectory into memory. 
So which is it? 

If you don't have enough memory to load a single trajectory into memory then we cannot help you because HTMD needs to read a trajectory into memory first before dropping frames. 
PyEMMA supports streaming trajectories from disk to memory as far as I remember so you could try that.

If you have enough memory to load the single trajectory to memory then the problem is possibly that Metric.project() is loading multiple trajectories in parallel since HTMD is parallelized by default. You could try setting the number of CPUs to 1 to see if that helps:

```
from htmd.config import config
config(ncpus=1)
```

**Comment by stefdoerr** [comment]
Actually sorry, it probably is due to parallelization.
If you can load 1 trajectory into memory with `Molecule('traj.xtc')` then the problem is that simfilter and Metric() read multiple trajectories in parallel. Try the above command I sent you to set the ncpus to 1

**Comment by piia600** [comment]
I think the trajectory is too large to be loaded into memory, since using only one CPU didn't help. However, it is around 9GB in size, and I should have enough memory to load that all in there at the same time (before starting any calculation I had about 14GB free memory). Or should it take somehow more memory in RAM than it takes on the hard disk?

**Comment by stefdoerr** [comment]
Not really.
Try loading it directly into a Molecule to see if it works.
`mol = Molecule('yourtraj.xtc')`

If that crashes then we probably can't help much further :( Maybe you can try to filter with some other software and then use HTMD on the filtered trajectories.

**Comment by stefdoerr** [comment]
Actually, what file type is your trajectory?
I can imagine that for some filetypes the reader reads the frames separately into a list which then gets concatenated into an array. That would exactly double the memory and hence explain the problem.

**Comment by piia600** [comment]
The trajectory is a xtc from AceMD. I think that you might be right about the doubling of the memory consumption, since I am unable to load even one full trajectory.

I will try to split/filter the simulations with cpptraj or something.

**Comment by stefdoerr** [comment]
Yeah, I'm sorry that we cannot handle such edge cases. We have built HTMD a bit on the idea of high-throughput (and thus typically short length) MD simulations and are missing some optimizations for such cases.
Try filtering/frameskipping with some other software as you say and then you can probably come back to HTMD for the rest if you still feel like it :)

**Comment by tonigi** [comment]
You can decimate frames with gromacs' trjconv . Consider that the xtc format are well compressed, and memory requirements may be 10x or more the disk size.
