### ISSUE TITLE
adaptive sampling benzamidine/trypsin unbinding example

### ISSUE THREAD

**Issue by amrhamedp** [Acellera/htmd#558]
Hello ,
I can't find the python notebook described in workshop:
https://www.youtube.com/watch?v=mvL6jxyWhn8&index=8&list=PLDYs662FgoLO-wPIerFTidunlj8uUIzZO
can you please tell me where it is?

**Comment by stefdoerr** [comment]
We have a general adaptive samling tutorial here
https://software.acellera.com/docs/latest/htmd/tutorials/adaptive-sampling.html
The specific one for ben tryp I am not sure if we have anymore. But it
should not really matter.
The only thing you really need to set up for adaptive are the metrics you
use and in the case of adaptive goal also the goal function.

In any case if you have any specific questions on how to use it just feel
free to ask

**Comment by amrhamedp** [comment]
In my case, i need to use htmd to verify which pose of a ligand ( from a docking study) is more stable. I thought about using adaptive sampling starting from the poses i have. However, I need some advice regarding the goal function to be used  and the analysis that should be performed .

**Comment by stefdoerr** [comment]
Well, there are many ways of doing it. You could also use our KDeep method
http://www.playmolecule.org/Kdeep/
Otherwise if you really want to do it by adaptive simulations, since you are already starting from the bound poses and you want to get stability you could try some general unbinding goal method like maximizing the total distance of the ligand to the protein. Then you would need to build an MSM to obtain equilibrium stability of the bound pose vs unbound.

**Comment by j3mdamas** [comment]
Hi @amrhamedp,

The tutorial on the Benzamidine-Trypsin exercise is not available, as Stefan mentioned, but the general adaptive is available. Specifically, here: https://raw.githubusercontent.com/Acellera/htmd/1.11.2/tutorials/adaptive-sampling.ipynb

As the follow-up is not an issue with HTMD in particular, I will close this thread. Feel free to contact us if you face any issues setting up your metrics or goal functions.

Best,
João
