### ISSUE TITLE
Creation of generetors from equilibrated system failing.

### ISSUE THREAD

**Issue by alejandrovr** [Acellera/htmd#59]
We have build a system using docking to initialize positions, then we equilibrate it. We try to create the generators using this code:

```python
from htmd.protocols.production_v1 import Production
md = Production()
md.acemd.run = '50ns'
md.temperature = 298
equils = natsorted(glob('docked/equil/*/'))
for i, b in enumerate(equils):
    md.write(b, 'docked/generators/{}/'.format(i+1))
mdx = AcemdLocal()
mdx.submit(glob('./docked/generators/*/'))
mdx.wait()
```

But when we use the file in equil folder as input to the generators function it fails and gives the error:
`FileNotFoundError: [Errno 2] No such file or directory: 'docked/equil/1/input.xsc'`

We think that maybe the problem is that we have an input file but it does not have .xsc extension. We add this extension to our input file and then we could continue, but in the final xcd.wait() command we had other problem:
```
2016-06-10 15:16:34,061 - htmd.apps.acemdlocal - ERROR - Error in ACEMD for path: /home/student1/avarela/docking_tutorial/docked/generators/1. Check the /home/student1/avarela/docking_tutorial/docked/generators/1/log.txt file.
```

Do you have any suggestion of what can we do? We are following this tutorial: https://www.htmd.org/docs/tutorials/docking-simulation-generators.html and it gives the same error.

Thanks in advance,

Alejandro.

**Comment by stefdoerr** [comment]
No, the `input.xsc` is a different file than the `input` and if you rename it it will break everything. The xsc file contains the box size of your system after equilibration and is needed to start production runs because otherwise ACEMD does not know what the box size of your system is.

As you can see in [the tutorial](https://www.htmd.org/docs/tutorials/mu-opioid-receptor-gpcr-equilibration.html), after doing equilibration, to start a production run you need to specify the names of your equilibration `output.xsc` and `.coor` files.

**Comment by stefdoerr** [comment]
Also a tip, format your code with 
\`\`\`python
ace=AcemdLocal()
\`\`\`
Then it's more readable ;)
