### ISSUE TITLE
Amber Builder: Box parameters missing in inpcrd

### ISSUE THREAD

**Issue by andt88** [Acellera/htmd#762]
I am trying to built a system with HTMD to simulate it using Amber16's pmemd.
Is there a way to include the box information in the prmtop and crd files when building the system?
Right now I am getting the error 'ERROR:   Box parameters not found in inpcrd file!'

**Comment by andt88** [comment]
I’m not sure which of the input files you are referring to. It’s not straightforward to my knowledge to add box parameters to crd files. My workaround right now is to convert crd and prmtop output from HTMD to pdb, load the pdb into tleap again and use the setbox command to add the box parameters.
If it were possible to edit the HTMD tleap input file to add setbox there, it would produce the crd file with box parameters directly.

**Comment by stefdoerr** [comment]
I don't like it design wise unfortunately :( Our builders don't care about simulation details. They just build the system. The simulation configuration is done by the `Equilibration` and `Production` classes. So if we move box size to the builder for `tleap` it will make the design inconsistent.

**Comment by j3mdamas** [comment]
Yeah, I think there's a clear difference here between ACEMD and pmemd/sander: ACEMD considers the box a simulation detail while pmemd/sander does not. I was just checking the documentation of pmemd/sander, and there seems to be no way to define the box there (in the simulation details).

We're left with the decision if we want `amber.build` to be mdengine agnostic or not. If I recall it correctly, even though the box may be set explicitly, normally we calculate it on-the-fly on the ACEMD simulation protocol classes. What we can do, like you suggested, is to move this on-the-fly calculation to `amber.build` and in the ACEMD simulation protocol classes, we set it again, because that part of the prmtop/incrd is not read by ACEMD. If we're feeling particularly fancy, we may issue a warning (even though I don't think it's necessary)

**Comment by j3mdamas** [comment]
Sometimes I forget ACEMD was "inspired" in NAMD. It can be seen [here](https://www.ks.uiuc.edu/Research/namd/2.9/ug/node13.html):
> 4. NAMD does not read periodic box lengths in PARM or coordinate file. They must be explicitly specified in NAMD configuration file.

**Comment by stefdoerr** [comment]
@andt88 we fixed it now to write the box size in the CRD

**Comment by andt88** [comment]
Great! Thanks a lot? Is this by default?

**Comment by stefdoerr** [comment]
Yes

On August 29, 2018 7:57:55 PM GMT+03:00, andt88 <notifications@github.com> wrote:
>Great! Thanks a lot? Is this by default?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/Acellera/htmd/issues/762#issuecomment-417027047

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
