### ISSUE TITLE
Error: "TCL error at line #1 [can't read "coords(g105363488)": no such variable]

### ISSUE THREAD

**Issue by KendyP** [Acellera/htmd#79]
Hello,
I've posted before about an error with this system during equilibration. Unfortunately, I'm receiving a different error now. 
The single bilayer system contains a homology model created using I-Tasser. The system is built with HTMD in an ipython notebook with no errors. Initial visualization does not show anything out of the ordinary. When equilibrating the system, there is an error (title of this post) at the beginning of minimization. 

I've attached the notebook used, as well as the log and error files from equilibration. Any help is greatly appreciated. 

Thanks
Kendy
[Error-KP.zip](https://github.com/Acellera/htmd/files/348662/Error-KP.zip)

**Comment by stefdoerr** [comment]
I am looking at it now. I don't know if it's on purpose but you are going to have some issues with this homology model. If you look at autosegment it splits the protein into 12 segments because it has gaps in the resids. First residue has resid 8, second has 25 and they are not in order (not bonded). So unless you were actually planning to simulate the protein with another 10 residues flying around it's probably not correct. `charmm.build()` will add caps to each of those 10 individual residues because they are recognized as separate segments, which will make it even worse I assume.

The error I assume comes from the fact that you are defining the box of a flat bottom potential but you are not specifying which atoms to restrict in that box. Did you actually want to add a flat bottom potential or were you confused by the naming of `eq.box`? I actually renamed it to `eq.fb_box` in Equilibration_v2 because it was confusing lots of people.

**Comment by giadefa** [comment]
the problem is your notebook.

#md.reference = 'protein and resid 293'
#md.selection = 'segname L and noh'
md.box = [-60.4, 59.3, -65.6, 66.3, -40.3, 38.7] #these will be changed
according to system dimensions before equilibration
md.k = 5

you cannot assign an empty reference and selection if you want to have a
flatbottom potential. Are you sure that you want a flatbottom potential? Do
you need to restrain a ligand in a box?

On 6 July 2016 at 10:39, Stefan <notifications@github.com> wrote:

> I am looking at it now. I don't know if it's on purpose but you are going
> to have some issues with this homology model. If you look at autosegment it
> splits the protein into 12 segments because it has gaps in the resids.
> First residue has resid 8, second has 25 and they are not in order (not
> bonded). So unless you were actually planning to simulate the protein with
> another 10 residues flying around it's probably not correct.
> charmm.build() will add caps to each of those 10 individual residues
> because they are recognized as separate segments, which will make it even
> worse I assume.
>
> The error I assume comes from the fact that you are defining the box of a
> flat bottom potential but you are not specifying which atoms to restrict in
> that box. Did you actually want to add a flat bottom potential or were you
> confused by the naming of eq.box? I actually renamed it to eq.fb_box in
> Equilibration_v2 because it was confusing lots of people.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Acellera/htmd/issues/79#issuecomment-230712529>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AHaqOu082gEP-Bq8BtpKowwvgmWiRlGyks5qS2nKgaJpZM4JFizy>
> .
>



-- 
<http://www.acellera.com>

       <https://twitter.com/acellera>
<https://www.youtube.com/user/acelleracom>
<https://www.linkedin.com/company/2133167?trk=tyah&trkInfo=clickedVertical%3Acompany%2CclickedEntityId%3A2133167%2Cidx%3A2-1-2%2CtarId%3A1448018583204%2Ctas%3Aacellera>
    <https://www.acellera.com/md-simulation-blog-news/>
<http://is.gd/1eXkbS>

**Comment by KendyP** [comment]
Thank you for your responses. We are taking a look at our homology model now. I misunderstood the md.box command and will adjust the notebook accordingly. I greatly appreciate your help.
