### ISSUE TITLE
Not ableto proceed to the next epoch

### ISSUE THREAD

**Issue by anuginu** [Acellera/htmd#841]
I am trying to run adaptive sampling on protein-drug complex using HTMD and gromacs. It is completing the first epoch but not proceeding to the next epoch. It is giving the error "ValueError: invalid literal for int() with base 10: '37A'" Please find the attached folder used as input (one of the starting positions in the folder generators) to start the sampling and the error obtained after the first epoch. Kindly help.
[gen1.tar.gz](https://github.com/Acellera/htmd/files/2771533/gen1.tar.gz)
/home/anu/Desktop/Screenshot from 2019-01-17 10-06-01.png

**Comment by stefdoerr** [comment]
There seems to be an error in your PDB file. Try reading it directly with `mol = Molecule('mypdb.pdb')`. You probably have some misaligned columns. Check the PDB documentation on the specific columns

**Comment by anuginu** [comment]
Dear Stefan, 
I read the pdb file with mol = Molecule('2bm2_processed.pdb'). But there seems to be no error. While processing for the next epoch, if the residue number in the pdb is like 184,184A, 184B etc.. should the residue numbers be renumbered to overcome this error (ValueError: invalid literal for int() with base 10: '37A')?

**Comment by stefdoerr** [comment]
No, it should work with the insertion codes fine.
I checked the pdb files but they are not what you use for the simulation and they don't contain any 37A residue either.
Could you post here the full error log and maybe also a `data` directory from a completed simulation. I don't have much experience with gromacs but the `input` files don't help much in this case. 

I have a doubt though that HTMD and analyse your simulations since it depends on a single PDB file with the topology on which it will load the simulation trajectory. But an output folder might help me understand the problem better.

**Comment by anuginu** [comment]
Sorry for the late reply. I was caught up with some work and hence couldn't reply. The filtered output was not created as the input folder contained pdb file with residues having ids like '37A'. (The orginal pdb file was download from RCSB but was given some modificationto have different starting structure using Avogadro software). when I renumbered the resid, it proceeded to the next epoch. 

I have a doubt about the starting structures for adaptive sampling..why in protein-ligand simulations the ligand is always placed at 20 Angstroms away? When the ligand -binding site is known, what is the advantage in using adaptive sampling ? Can adaptive sampling be used to give better free energy binding values when a ligand-docked structure is used ? Please clarify.

**Comment by stefdoerr** [comment]
The 20A is just to not add much bias to the starting conformation. Usually we distribute it around the protein as well to have multiple generator (starting) structures for adaptive.
Depending on which adaptive sampling method you use it might speed up binding or unbinding or whatever process you want to sample faster.
If you have a docked pose you can use that as well as your starting point. But take care because if it's a strong binder it might take very long to unbind. Depends which process you want to sample really. 
I don't know if this answers your questions.

**Comment by stefdoerr** [comment]
If you start from multiple poses you will have the problem what you won't have connections between the states. Thus if you use adaptive sampling it will build an MSM out of the largest connected set of states and discard the rest. This is quite inefficient as it's equivalent to starting from a single pose.

In your case you don't want to build an MSM and instead spawn new simulations with a different strategy until all your states are connected. Then you can switch to standard adaptive sampling. But for that you would have to play around a bit with the adaptive sampling implementation.

I remember there is a paper by Vijay Pande on adaptive sampling from bound unbound and intermediate states where they manually move the ligand out of the pocket and then start adaptive simulations but I can't remember the title, you will have to search for it.
