### ISSUE TITLE
Adaptive Sampling: Tracing the longest path between current and parent simulation

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#842]
Hi

I have two questions:

Is there an automated way we can find out the longest path (current sim to parent sim) to construct a single trajectory in adaptive sampling? 

Is there a reason when generating a long trajectory, the number of frames (numframes) are not printed in last sim.? I have checked and its fine with 500 frames. 

Creating simlist: 100%|██████████| 14/14 [00:00<00:00, 3572.88it/s]
.......
 
simid = 11
parent = None
input = ./input/e9s1_e6s1p0f361/
trajectory = ['./data/e9s1_e6s1p0f361/trajectory.xtc']
molfile = ./input/e9s1_e6s1p0f361/structure.pdb
numframes = [500]
,
simid = 12
parent = None
input = ./input/e10s1_e2s1p0f333/
trajectory = ['./data/e10s1_e2s1p0f333/trajectory.xtc']
molfile = ./input/e10s1_e2s1p0f333/structure.pdb
numframes = [None]

Many thanks.

Shozeb

**Comment by stefdoerr** [comment]
Yes indeed. `from htmd.adaptive.adaptive import reconstructAdaptiveTraj`
https://github.com/Acellera/htmd/blob/master/htmd/adaptive/adaptive.py#L288

The missing number of frames is weird but it's simply because the trajectory has not been read yet by HTMD to generate the hidden number of frames file. If you read it once with Molecule for example it should detect them fine afterwards.

**Comment by shozebhaider** [comment]
Many thanks.
