### ISSUE TITLE
Documentation of queue properties

### ISSUE THREAD

**Issue by tonigi** [Acellera/htmd#858]
Minor issue in the documentation: in the help of LocalGPUQueue https://software.acellera.com/docs/latest/htmd/htmd.queues.localqueue.html  options such as `devices` look like  constructor parameters (they are listed under "parameters"). Instead they only seem to works as properties of the object (can only be set after creation).

**Comment by stefdoerr** [comment]
I don't agree. When they are parameters they look like this:
https://software.acellera.com/docs/latest/htmd/htmd.molecule.molecule.html
`class htmd.molecule.molecule.Molecule(filename=None, name=None, **kwargs)`
So they are in the constructor signature. The only issue for me is that they are called parameters instead of maybe attributes like some of the attributes defined later on.
