### ISSUE TITLE
proteinPrepare does not handle subclasses

### ISSUE THREAD

**Issue by aqred1** [Acellera/htmd#877]
FYI
ProteinPrepare always returns a Molecule object, even when passing a Molecule subclass as an argument.
```
class mynewClass(Molecule):
   [...]

a=mynewClass()
b=proteinPrepare(a)
```
b is now a Molecule object, not a mynewClass object.
Most likely comes from _fillMolecule() which creates a Molecule() anew.

**Comment by stefdoerr** [comment]
Yes, various functions return `Molecule` objects instead of the passed type. I didn't really envision this usage. Is it possible for you to convert it back to the subclass after calling `proteinPrepare`? Otherwise I could try to make it work with subclasses but it seems a very low priority task for me.

**Comment by giadefa** [comment]
Hi, would you be able to make a pull request yourself?

Would be ok to just copy the class inside protein prepare instead of
creating a new one?

The other alternative is to wrap molecule in your class instead of
subclassing it

**Comment by stefdoerr** [comment]
Yes, you could change proteinPrepare to copy the object, remove all of it's atoms and make it add the new atoms back in as @giadefa suggests.

**Comment by aqred1** [comment]
No problem, I can write a wrapper around `proteinPrepare` that converts again to my subclass.
Thanks.

**Comment by j3mdamas** [comment]
I think this is solved. Closing.
