### ISSUE TITLE
manipulating trajectories

### ISSUE THREAD

**Issue by shozebhaider** [Acellera/htmd#878]
I want to simulate a protein-ligand complex for 500ns. From this I want to extract snapshots at every 50ns intervals (50ns, 100ns, 150ns ... 450ns) that contain velocity information so that I can rerun simulations it from that point onwards. 
(a) What would be the best format that can rewrite xsc, vel, idx, and coor files at that time stamp after the simulation has ended ? 
(b) I then want to remove the ligand and then rerun the simulation again retaining the box info, velocity and other bits as in the parent simulation. (binding site but now devoid of the ligand)

Many thanks.

**Comment by stefdoerr** [comment]
For a) I would just run the simulation in pieces. I.e. do a simulation of 50ns, then change the input file to 100ns, then change the input file to 150ns etc and at every step copy the output.xsc output.vel etc to a new folder.

I don't think b) is doable. Removing the ligand creates vacuum which needs to be filled. If you maintain NVT the pressure will be wrong. If you do NPT it will need to equilibrate to fill the vacuum. You could add waters into the vacuum but I would still do equilibration since the protein will change conformation.

**Comment by shozebhaider** [comment]
Many thanks.
