### ISSUE TITLE
Questions: AdaptiveGoal method

### ISSUE THREAD

**Issue by smar966** [Acellera/htmd#901]
Hello,

I am trying to implement the AdaptiveGoal approach on my systems, and for now I'm testing it with a very basic function, just the distance of the ligand to the active site.

I currently have the 'adaptive_goal.py' script for that (built based on the documentation; see below), which seems to be running fine. Let's assume that I am only interested is observing the release of the ligand.

My questions are:
1) if I define the 'adg.goalfunction', then why do I need to define also the 'adg.projection'? (I've tried to exclude it and the script crashed).
2) If I define those functions differently (for example: adg.projection = MetricSelfDistance('protein and name CA') ), how will that affect my adaptive simulations and the way the ligand release is achieved?

Thank you in advance!
Best regards,
Sergio Marques

>>
adaptive_goal.py
>>
from htmd.ui import *
# Adaptive Goal

adg = AdaptiveGoal()
adg.nmin = 1
adg.nmax = 3
adg.nepochs = 3
adg.generatorspath = './generators'

adg.projection = MetricDistance('resname MOL and name Cl1', 'resid 104 and name CG', metric='distances')

adg.ticadim = 1
adg.app = LocalGPUQueue()
adg.dryrun = True

# Goal function for the ligand distance
def mygoalfunction(mol):
    dist = MetricDistance('resname MOL and name Cl1', 'resid 104 and name CG', metric='distances').project(mol)
    return dist  # the goal is to achieve the highest value of this function

adg.goalfunction = mygoalfunction

adg.run()

**Comment by stefdoerr** [comment]
So, adaptive goal works by doing both exploration and exploitation. The
exploitation part is the goal where you exploit some knowledge to guide the
sampling. The exploration part is where you try to discover new states
which you have not seen before agnostically. These two components get
balanced with a factor which decides how much exploring or exploiting you
want to do.

The exploration part requires the construction of a Markov state model to
define states so that it can sample from the least populated states. For
the MSM to define states it needs to project your data on a lower dimension
to cluster it and hence the projection.
It doesn't need to be the same as the goal but if you want it can be. It
must be a projection that allows the MSM to separate different system
configurations well so that it can the cluster it into states and sample
from the least populated ones. I hope this explanation helps a bit.

**Comment by smar966** [comment]
Hi Stefan,
That clarified a lot, thanks!
Can you tell me more about that balance factor? What is the default and how can I change it? 
Imagine that I want to observe a very rare event, how can I increase the exploitation to the maximum for highest efficiency?

**Comment by stefdoerr** [comment]
Sure, the balance factor is called `ucscale` as you can find here in the docs https://software.acellera.com/docs/latest/htmd/htmd.adaptive.adaptivegoal.html 
If you turn it to the maximum though it will ignore your goal. At that point you can also just use `AdaptiveRun` which does just exploration.

**Comment by stefdoerr** [comment]
Sorry, the terms might be a bit confusing. I sometimes call them interchangeably exploration/undirected and exploitation/goal/directed components.

**Comment by smar966** [comment]
I assume the ucscale can take values between 0 and 1, right?
In that case, is the 'nosampledc = True' the same as 'ucscale = 0'?

**Comment by stefdoerr** [comment]
yes ucscale goes from 0 to 1.
No `nosampledc` is a different option for if you want to take directly the
most highest scoring goal poses or sample from the distribution of goal
scores which provides more variety and might get less stuck. If you insist
on always following your maximum current goal score conformation you could
get stuck. I think the `nosampledc` option was quite experimental and maybe
I should remove it or hide it

**Comment by smar966** [comment]
OK, understood. I think all is clear now. 
Thanks a lot, Stefan! :)
