### ISSUE TITLE
Constant registration asking

### ISSUE THREAD

**Issue by piia600** [Acellera/htmd#909]
Hi,

I am trying to use HTMD for analysis and starting some new sets of simulations. Since few days ago, the registration is somehow bugged and appears every time I try to run anything on my pc or via ssh on the supercomputer (these systems are not connected and even the versions differ a bit). Obviously, this breaks all the scripts and it is very frustrating to fill in the registration form for every usage of HTMD. I hope you can help me.

Cheers,
Piia

**Comment by stefdoerr** [comment]
Yes, I am trying to fix it hopefully by tomorrow. The validation server is failing due to a migration. Thanks for confirming though because for a moment I thought it was just my issue.

You can avoid it by using absolute imports but it's a bit of a hassle if you use lots of HTMD stuff.
So instead of `from htmd.ui import *` you would do: `from htmd.builders import charmm` for example, but you would need to do it for all your imports.

**Comment by piia600** [comment]
Ok, thanks for the info. Please ignore Jesus from the institute of "how many times do I need to do this" :D I might have gotten frustrated at some point.

**Comment by stefdoerr** [comment]
Ok I disabled the check until I figure out (hopefully tomorrow what's up). Sorry for the annoyance, believe me, it was driving me crazy as well :P

**Comment by stefdoerr** [comment]
I fixed it now by restoring the DB. You might have to register one more (and hopefully last) time. I apologize for the trouble.
