### ISSUE TITLE
Differences between `pdb2pqr` as standalone and via htmd

### ISSUE THREAD

**Issue by aanastasiou** [Acellera/htmd#980]
There seem to be some differences between the standalone version of pdb2pqr and the one provided by htmd and I was wondering what these differences are due to (?).

As we can see [here](https://pypi.org/search/?q=pdb2pqr), there are 3 versions with slight differences:

1. The standalone `pdb2pqr` does not have any "extensions" and also, does not list `--ph-calc-method` as a parameter
2. The htmd version includes a number of "extensions" to output hydrogen bonds, contacts, salt bridges etc.
3. The standalone version provides a `pdb2pqr30` while the htmd one provides a `pdb2pqr_cli` 

Is it possible to clarify what these differences are due to please? On the htmd provided pdb2pqr, `extensions` is a package, but it is not there on the standlone `pdb2pqr`. Is that a separate dependency?

I am interested in those extensions which seem to be listed on precompiled versions (e.g. the one that is available on Debian) but not there across all uses of pdb2pqr.

**Comment by stefdoerr** [comment]
Γειά σου Θανάση :)
Tricky question because I've not kept up with it. I would suggest you use the official version since they have updated it recently to 3.0. Ours is a fork from 2.1.1 version with some fixes. Specifically I remember fixing one issue where the added atoms were just copying the element of the first atom of the residue it was being added to, so the hydrogens would end up having carbon element which caused some issues in our pipeline. But they might have fixed this since then in the official version. 
I'm not sure what the `extensions` package is for, sorry

**Comment by aanastasiou** [comment]
Γειά σου Στέφανε! :)

The 3.0.0 seems to have renamed some options (which is fine) but the options on listing hydrogen bonds, contacts and salt bridges are not there. The 2.1.1 [has those options but it also includes `extensions`](https://packages.debian.org/sid/amd64/pdb2pqr/filelist) which is not there in 3.0.0. But I might ask over at `pdb2pqr`. 

Thank you anyway, it was an opportunity for me to get to know about htmd too :)

All the best
