### ISSUE TITLE
Issues installing in

### ISSUE THREAD

**Issue by phisanti** [Acellera/htmd#986]
Hi,

I am having some problems installing HTMD. This is what I see. I am running a virtual machine with Ubuntu 16, tho I also tried ubuntu 18.
![image](https://user-images.githubusercontent.com/33370667/106366734-e1582980-6335-11eb-96ec-db24e5d64fe1.png)
Also, I tried python 3.6,  3.7, 3.7.9 and 3.8.
Any suggestion?

**Comment by giadefa** [comment]
Follow the installation instructions:
conda install -c acellera -c psi4 -c conda-forge htmd

**Comment by phisanti** [comment]
Not much of a change. 
![image](https://user-images.githubusercontent.com/33370667/106367404-52014500-633a-11eb-85e6-a84860040d47.png)

It stays "solving environment" forever.

**Comment by stefdoerr** [comment]
Patience. Conda is extremely slow at solving dependencies and sometimes if
there are connection issues or a server is down it can take forever.
Otherwise yes it should install fine with these commands
You could alternatively try mamba which is a faster dependency solver than
conda and is installable via conda

conda install mamba -c conda-forge
mamba install python=3.6 htmd propka=3.1.8 -c acellera -c psi4 -c
conda-forge

**Comment by phisanti** [comment]
Yupp, the issue is close. Thanks a lot!
