### ISSUE TITLE
Restrict water molecules placement

### ISSUE THREAD

**Issue by phisanti** [Acellera/htmd#989]
Hi, I am following this tutorial https://software.acellera.com/docs/latest/htmd/tutorials/system-building-protein-in-membrane.html. Currently, I got the psf file and everything goes apparently right. However, I have noticed a funny detail. When building the water box, the visualisation shows some water molecules among the lipid membrane. As the lipid membrane of the example is not provided, I build one (see issue #988). Thus, I was wondering if there is a method to restrict the placement of water molecules so that they don't appear in the lipid vicinity.

**Comment by stefdoerr** [comment]
You can but you might also simply not care. We regularly build membranes with some water inside and during the default restrained equilibration all the water is expelled quite quickly.

If you really still care though you can define max min coordinates for your solvation box in `solvate`. In that case you would solvate twice, once up to the upper atoms of the membrane and a second time from below the lowest atoms of the membrane. It's more work though and usually not necessary since as I said the equilibration fixes it.

**Comment by phisanti** [comment]
Okay, thanks!
